{
  description = "Home Manager configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";  # use same nixpkgs version
    };
  };

  outputs = { nixpkgs, home-manager, ... }:
    let
      system = "x86_64-linux";  # or "aarch64-linux", "aarch64-darwin"
      pkgs = nixpkgs.legacyPackages.${system};

      # Load user config automatically from ../user-config.nix (generated by run.sh)
      # Falls back to placeholders if file doesn't exist
      userConfig = if builtins.pathExists ../user-config.nix then import ../user-config.nix else {};
      username = userConfig.username or "user";
      homeDirectory = userConfig.homeDirectory or "/home/user";
    in {
      homeConfigurations."${username}" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [
          {
            _module.args = {
              inherit username homeDirectory;
            };
          }
          ./home.nix
          ./fish/fish.nix
          ./tmux/tmux.nix
          ../nvim/nvim.nix
        ];
      };

      # Expose individual modules so they can be imported from other flakes
      homeModules = {
        fish    = import ./fish/fish.nix;
        tmux    = import ./tmux/tmux.nix;
        neovim  = import ../nvim/nvim.nix;
      };
    };
}
