{
  description = "Nix and dotfiles configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # llm-agents.url = "github:numtide/llm-agents.nix";

    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nixvim = {
      url = "github:nix-community/nixvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      nixpkgs,
      disko,
      home-manager,
      nixvim,
      ...
    }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
      };
      neovimModule = {
        _module.args = {
          nixvimLib = nixvim.lib.nixvim;
          nvimPkgs = pkgs;
        };
        imports = [
          nixvim.homeModules.nixvim
          ./config/nvim/nvim.nix
        ];
      };

      # Load user config automatically from user-config.nix (generated by run.sh)
      # Falls back to placeholders if file doesn't exist
      userConfig = if builtins.pathExists ./user-config.nix then import ./user-config.nix else { };
      username = userConfig.username or "user";
      homeDirectory = userConfig.homeDirectory or "/home/user";

      nixosConfigurations =
        (import ./nixosAnywhere {
          inherit system username;
          inputs = {
            inherit nixpkgs disko;
          };
        })
        // (
          if builtins.pathExists ./nixosAnywhere/local/default.nix then
            import ./nixosAnywhere/local {
              inherit system username;
              inputs = {
                inherit nixpkgs disko;
              };
            }
          else
            { }
        );

    in
    {
      homeConfigurations."${username}" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [
          {
            _module.args = {
              inherit username homeDirectory;
            };
          }
          ./config/home.nix
          ./config/packages.nix
          {
            home.packages = [ pkgs.devbox ];
          }
          ./config/environment.nix
          ./tooling/tooling.nix
          neovimModule
          ./config/tmux/tmux.nix
          ./config/bash/bash.nix
          ./config/starship/starship.nix
          ./config/kde.nix
          ./nixosModules/coding-agents/pi.nix

        ];
      };

      inherit nixosConfigurations;

      homeModules = {
        packages = import ./config/packages.nix;
        environment = import ./config/environment.nix;
        bash = import ./config/bash/bash.nix;
        starship = import ./config/starship/starship.nix;
        kde = import ./config/kde.nix;
        tmux = import ./config/tmux/tmux.nix;
        neovim = neovimModule;
        tooling = import ./tooling/tooling.nix;
      };
    };
}
