{
  description = "Nix and dotfiles configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # llm-agents.url = "github:numtide/llm-agents.nix";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { nixpkgs, home-manager, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};

      # Load user config automatically from user-config.nix (generated by run.sh)
      # Falls back to placeholders if file doesn't exist
      userConfig = if builtins.pathExists ./user-config.nix then import ./user-config.nix else {};
      username = userConfig.username or "user";
      homeDirectory = userConfig.homeDirectory or "/home/user";
    in
    {
      homeConfigurations."${username}" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [
          {
            _module.args = {
              inherit username homeDirectory;
            };
          }
          ./config/home.nix
          ./config/packages.nix
          ./config/environment.nix
          ./tooling/tooling.nix
          ./config/nvim/nvim.nix
          ./config/tmux/tmux.nix
          ./config/bash/bash.nix
          ./config/starship/starship.nix
          ./packages/coding-agents/pi.nix
        ];
      };


      homeModules = {
        packages = import ./config/packages.nix;
        environment = import ./config/environment.nix;
        bash = import ./config/bash/bash.nix;
        starship = import ./config/starship/starship.nix;
        tmux = import ./config/tmux/tmux.nix;
        neovim = import ./config/nvim/nvim.nix;
        tooling = import ./tooling/tooling.nix;
      };
    };
}
