{
  description = "Nix and dotfiles configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { nixpkgs, home-manager, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};

      # Load user config automatically from user-config.nix (generated by run.sh)
      # Falls back to placeholders if file doesn't exist
      userConfig = if builtins.pathExists ./user-config.nix then import ./user-config.nix else {};
      username = userConfig.username or "user";
      homeDirectory = userConfig.homeDirectory or "/home/user";
    in
    {
      homeConfigurations."${username}" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [
          {
            _module.args = {
              inherit username homeDirectory;
            };
          }
          ./dotfiles/home.nix
          ./dotfiles/packages.nix
          ./dotfiles/environment.nix
          ./tooling/tooling.nix
          ./nvim/nvim.nix
          ./dotfiles/tmux/tmux.nix
          ./dotfiles/bash/bash.nix
          ./dotfiles/starship/starship.nix
          ./coding-agents/pi.nix
        ];
      };


      homeModules = {
        packages = import ./dotfiles/packages.nix;
        environment = import ./dotfiles/environment.nix;
        bash = import ./dotfiles/bash/bash.nix;
        starship = import ./dotfiles/starship/starship.nix;
        tmux = import ./dotfiles/tmux/tmux.nix;
        neovim = import ./nvim/nvim.nix;
        tooling = import ./tooling/tooling.nix;
      };
    };
}
