{ nvimPkgs, ... }: {
  programs.nixvim.extraPackages = with nvimPkgs; [
    gcc
    stylua
    gnumake
    imagemagick
    gnuplot
    lua
    luarocks
    go
    gotools
    ruff
    basedpyright
    selene
    delve
    isort
    black
    pyrefly
    ansible-lint
    python3Packages.debugpy
    python3Packages.ty
    ansible-language-server
    bash-language-server
    gopls
    helm-ls
    lua-language-server
    nixfmt
    shellcheck
    shfmt
    taplo
    terraform
    terraform-ls
    tflint
    yamlfmt
    yamllint
    yaml-language-server
    vscode-langservers-extracted
  ];
}
