# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  pi-coding-agent-arm64 = {
    pname = "pi-coding-agent-arm64";
    version = "v0.80.2";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.80.2/pi-linux-arm64.tar.gz";
      sha256 = "sha256-Bxns9QpCyuefTG8NSmLgjo1EIXiMzQUNCKW781yI7fY=";
    };
  };
  pi-coding-agent-x64 = {
    pname = "pi-coding-agent-x64";
    version = "v0.80.2";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.80.2/pi-linux-x64.tar.gz";
      sha256 = "sha256-Lmh3K76qzXNIh1EJgZOHU4lja4BYkQBgmimSHe1xyYQ=";
    };
  };
}
