#!/usr/bin/env bash

set -o pipefail

# Outputs the contents of a Kubernetes secret with base64-encoded data decoded.
# Mimics the output style of 'kubectl get secret' but with human-readable values.
kubectl-plain-secrets() {
    kubectl get secret "$@" -o json \
        | jq 'del(.metadata.annotations) | .data |= with_entries(.value |= @base64d)' \
        | yq -Cy \
        | bat -ppl YAML
}

kubectl-plain-secrets "$@"
