#!/usr/bin/env bash
if [[ -z "${1}" ]]; then
    namespaces="$(kubectl get namespaces -o name | cut -d/ -f2 | sort)"

    # choose with fzf
    namespace=$(echo "${namespaces}" | fzf)
else
    # remove final slash if present
    namespace="${1%/}"
fi

test -n "${namespace}" &&
    kubectl config set-context --current --namespace="${namespace}"
