#!/usr/bin/env bash
set -euo pipefail
# this is the simplest queue possible, using only built-in shell features (no external dependencies)
# It does not scale, but it works

# set by env or default to number of cores
MAX_JOBS=${MAX_JOBS:-$(nproc)}

sample_job() {
    echo "Running job $*"
    sleep 1
    echo "Finished job $*"
}

for i in {1..10}; do
    sample_job "$i" &
    if [[ $(jobs -r -p | wc -l) -ge $MAX_JOBS ]]; then
        wait -n
    fi
done

# # to clone github repos from a list:
# for repo in $(cat repos.txt); do
#     git clone "$repo" &
#     if [[ $(jobs -r -p | wc -l) -ge $MAX_JOBS ]]; then
#         wait -n
#     fi
# done