#!/usr/bin/env bash

repo="$(git remote -v 2>/dev/null | grep fetch | awk '{print $2}' | cut -d: -f2- | sed -e 's/.git//' | tr '[:upper:]' '[:lower:]')"

if [[ -n "$repo" ]]; then
    printf 'repo: %s\n' "$repo"
else
    basename "${PWD}"
fi
